# Lecture 04 

In [133]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Arithmetic

In [134]:
2 + 3

5

In [135]:
2 * 3

6

In [136]:
2 ** 3

8

In [137]:
2 * * 3

SyntaxError: invalid syntax (<ipython-input-137-0f343c0fc354>, line 1)

In [138]:
10 * 2 ** 3

80

In [139]:
2 / 3

0.6666666666666666

In [140]:
2 / 0

ZeroDivisionError: division by zero

In [141]:
2 / 3000

0.0006666666666666666

In [142]:
2 / 3000000

6.666666666666667e-07

In [143]:
0.6666666666666666 - 0.6666666666666666123456789

0.0

In [144]:
0.000000000000000123456789

1.23456789e-16

In [145]:
0.000000000000000000000000000000000000000000000000000000000000000000000123456789

1.23456789e-70

In [146]:
2 ** 0.5

1.4142135623730951

In [147]:
2 ** 0.5 * 2 ** 0.5

2.0000000000000004

In [148]:
2 ** 0.5 * 2 ** 0.5 - 2

4.440892098500626e-16

## Strings

In [152]:
'hello'

'hello'

In [153]:
'2.3'

'2.3'

In [154]:
'2.3' + 4

TypeError: can only concatenate str (not "int") to str

In [155]:
'2.3' * 4

'2.32.32.32.3'

In [169]:
float(2)

2.0

In [157]:
str(2.3)

'2.3'

In [159]:
int('2')*5

10

In [167]:
int(str(12)+'0')*2

240

In [161]:
x = 12
int(str(x) + '0')

120

## Arrays

Array:  sequence of values, all the same type, "boxed up"

In [170]:
make_array(1, 2, 'hello')

array(['1', '2', 'hello'], dtype='<U21')

In [179]:
max(4,7)


7

In [180]:
b = make_array(1,2,3)

In [173]:
b

array([1, 2, 3])

In [174]:
b*2

array([2, 4, 6])

Arithmetic operations are *broadcast*

In [181]:
a * 2

array([2, 4, 6])

In [182]:
a + 5

array([6, 7, 8])

In [184]:
make_array(1,2,3,4) + make_array(10, 100, 1000, 10_000)

array([   11,   102,  1003, 10004])

In [185]:
a

array([1, 2, 3])

In [188]:
length_of_a=len(a)
length_of_a

3

In [189]:
max(a)

3

In [190]:
min(a)

1

In [191]:
sum(a)

6

In [192]:
make_array(1,2,3) + make_array(1,2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

*Index* into array to retrieve items.  Indices start at 0.

In [ ]:
a.item(0)

In [ ]:
a.item(1)

In [ ]:
a.item(3)

Think of `item(n)` as asking for the item that has `n` items before it.

## Range

`np.arange`: a library function that produces an array containing a range of values

In [ ]:
np.arange(1, 5)

Range includes beginning, excludes ending:  $[1, 5)$

In [ ]:
b = np.arange(0, 20)
b

In [ ]:
c = np.arange(2,-2,-1)
c

## Columns

Table columns are arrays

In [ ]:
# From http://www.boxofficemojo.com/alltime/adjusted.htm
movies = Table.read_table('top_movies_2017.csv')
movies.show(15)

In [ ]:
movies.column('Year')

Let's make a table that also contains the age of the movie.  (2018 is 0 years old, 2017 is 1 year old, etc.)

In [ ]:
2018 - movies.column('Year')

In [ ]:
movies.with_column(
  'Age', 2018 - movies.column('Year')
)

In [ ]:
age = 2018 - movies.column('Year')
age

In [ ]:
movies = movies.with_column('Age', age)
movies

In [ ]:
movies.sort('Age').show(20)

How does age relate to proceeds?

In [ ]:
movies.scatter('Age', 'Gross')

In [ ]:
movies.scatter('Age', 'Gross (Adjusted)')